import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth,onAuthStateChanged,signOut } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore,collection,addDoc,updateDoc,deleteDoc,doc,serverTimestamp,increment,query,onSnapshot,setDoc,getDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const SUPERADMIN_EMAIL="facundoemmert@gmail.com",SUPERADMIN_UID="IArWgSKZF4a8eu0j3eoWS4el2P02";let usuarioActualData=null,objetivosCache=[];const formatoPesos=new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0});
function tienePermiso(p){return usuarioActualData&&(usuarioActualData.rol==="superadmin"||(usuarioActualData.permisos&&usuarioActualData.permisos[p]===true))}
async function cargarUsuario(user){const email=user.email.toLowerCase();if(email===SUPERADMIN_EMAIL||user.uid===SUPERADMIN_UID){usuarioActualData={uid:user.uid,nombre:"Facundo Emmert",email,rol:"superadmin",activo:true,permisos:{institucional:true,objetivos:true,obra:true,transparencia:true,usuarios:true}};await setDoc(doc(db,"admins",user.uid),{...usuarioActualData,actualizado:serverTimestamp()},{merge:true});return true}const a=await getDoc(doc(db,"admins",user.uid));if(a.exists()&&a.data().activo===true){usuarioActualData=a.data();return true}const inv=await getDoc(doc(db,"adminsByEmail",email));if(inv.exists()&&inv.data().activo===true){const d=inv.data();usuarioActualData={uid:user.uid,nombre:d.nombre||email,email,rol:"admin",activo:true,permisos:d.permisos||{}};await setDoc(doc(db,"admins",user.uid),{...usuarioActualData,actualizado:serverTimestamp()},{merge:true});return true}return false}
onAuthStateChanged(auth,async user=>{if(!user)return location.href="login.html";if(!await cargarUsuario(user)){await signOut(auth);return location.href="login.html"}document.getElementById("usuarioActual").textContent=`${usuarioActualData.nombre} - ${usuarioActualData.rol}`;document.getElementById("bloqueoAdmin").classList.add("oculto");document.getElementById("adminContenido").classList.remove("oculto");iniciar()});
document.getElementById("cerrarSesionBtn").onclick=async()=>{await signOut(auth);location.href="login.html"};
function iniciar(){tabs();permisos();config();objetivos();donaciones();obra();transparencia();usuarios()}
function tabs(){document.querySelectorAll(".tab-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab-btn").forEach(x=>x.classList.remove("activo"));document.querySelectorAll(".tab-panel").forEach(x=>x.classList.remove("activo"));b.classList.add("activo");document.getElementById(b.dataset.tab)?.classList.add("activo")})}
function permisos(){document.querySelectorAll("[data-permiso]").forEach(b=>{if(!tienePermiso(b.dataset.permiso))b.remove()});document.querySelectorAll("[data-panel-permiso]").forEach(p=>{if(!tienePermiso(p.dataset.panelPermiso))p.remove()});document.querySelector(".tab-btn")?.click()}
function config(){if(!tienePermiso("institucional"))return;const ref=doc(db,"configuracion","sitio"),f=document.getElementById("configForm");if(!f)return;onSnapshot(ref,s=>{if(!s.exists())return;const d=s.data();["nombreEscuela","subtituloEscuela","logoUrl","alias","cbu","titularCuenta","qrUrl","infoInstitucional"].forEach(id=>{const el=document.getElementById(id); if(el) el.value=d[id==="subtituloEscuela"?"subtitulo":id]||""});document.getElementById("nombreEscuelaAdmin").textContent=d.nombreEscuela||"Los Naranjos de la Concordia D-114";if(d.logoUrl){const l=document.getElementById("logoAdmin");l.src=d.logoUrl;l.classList.remove("oculto")}});f.onsubmit=async e=>{e.preventDefault();await setDoc(ref,{nombreEscuela:document.getElementById("nombreEscuela").value.trim(),subtitulo:document.getElementById("subtituloEscuela").value.trim(),logoUrl:document.getElementById("logoUrl").value.trim(),alias:document.getElementById("alias").value.trim(),cbu:document.getElementById("cbu").value.trim(),titularCuenta:document.getElementById("titularCuenta").value.trim(),qrUrl:document.getElementById("qrUrl").value.trim(),infoInstitucional:document.getElementById("infoInstitucional").value.trim(),actualizado:serverTimestamp()},{merge:true});alert("Información guardada")}}
function objetivos(){if(!tienePermiso("objetivos"))return;const f=document.getElementById("objetivoForm"),bus=document.getElementById("buscadorObjetivos");if(!f)return;f.onsubmit=async e=>{e.preventDefault();const precio=Number(document.getElementById("precio").value),rec=Number(document.getElementById("recaudado").value||0);await addDoc(collection(db,"objetivos"),{nombre:document.getElementById("nombre").value.trim(),descripcion:document.getElementById("descripcion").value.trim(),precio,recaudado:Math.min(rec,precio),imagenUrl:document.getElementById("imagenUrl").value.trim(),urgente:document.getElementById("urgente").checked,creado:serverTimestamp()});f.reset();document.getElementById("recaudado").value=0};onSnapshot(query(collection(db,"objetivos")),s=>{objetivosCache=[];s.forEach(d=>objetivosCache.push({id:d.id,...d.data()}));renderObjetivos()});bus.oninput=renderObjetivos}
function renderObjetivos(){const l=document.getElementById("listaObjetivos"),bus=document.getElementById("buscadorObjetivos");if(!l)return;const q=(bus?.value||"").toLowerCase();l.innerHTML="";objetivosCache.filter(o=>`${o.nombre||""} ${o.descripcion||""}`.toLowerCase().includes(q)).forEach(o=>{const precio=Number(o.precio||0),rec=Math.min(Number(o.recaudado||0),precio);const div=document.createElement("div");div.className="card";div.innerHTML=`<h3>${o.nombre}</h3><p>${o.descripcion||""}</p><p>Precio: ${formatoPesos.format(precio)}</p><p>Recaudado: ${formatoPesos.format(rec)}</p><p>Faltante: ${formatoPesos.format(Math.max(0,precio-rec))}</p><button onclick="editarObjetivo('${o.id}')">Editar</button><button class="btn-danger" onclick="eliminarObjetivo('${o.id}')">Eliminar</button>`;l.appendChild(div)})}
window.editarObjetivo=id=>alert("La edición completa la dejamos para el próximo ajuste. Para monto, usá aprobación de donaciones.");window.eliminarObjetivo=async id=>{if(confirm("¿Eliminar objetivo?"))await deleteDoc(doc(db,"objetivos",id))}
function donaciones(){if(!tienePermiso("objetivos"))return;const l=document.getElementById("listaDonacionesPendientes");if(!l)return;onSnapshot(query(collection(db,"donaciones")),s=>{l.innerHTML="";let n=0;s.forEach(d=>{const x=d.data();if(x.estado!=="pendiente")return;n++;const div=document.createElement("div");div.className="admin-card";div.innerHTML=`<div><h3>${x.objetivoNombre}</h3><p><strong>Donante:</strong> ${x.nombreDonante}</p><p><strong>Monto:</strong> ${formatoPesos.format(Number(x.monto||0))}</p><p><strong>Objetivo:</strong> ${x.objetivoNombre}</p><p><a href="${x.comprobanteUrl}" target="_blank">Ver comprobante</a></p></div><div class="admin-actions"><button onclick="aprobarDonacion('${d.id}','${x.objetivoId}',${Number(x.monto||0)})">Aceptar / Comprobado</button><button class="btn-danger" onclick="rechazarDonacion('${d.id}')">Rechazar</button></div>`;l.appendChild(div)});if(!n)l.innerHTML="<p>No hay donaciones pendientes.</p>"})}
window.aprobarDonacion=async(id,obj,m)=>{if(!confirm("¿Comprobaste que el dinero ingresó?"))return;await updateDoc(doc(db,"objetivos",obj),{recaudado:increment(m),actualizado:serverTimestamp()});await updateDoc(doc(db,"donaciones",id),{estado:"aprobada",aprobadoPor:usuarioActualData.email,aprobado:serverTimestamp()});alert("Donación aprobada y sumada.")};window.rechazarDonacion=async id=>{if(confirm("¿Rechazar?"))await updateDoc(doc(db,"donaciones",id),{estado:"rechazada",rechazadoPor:usuarioActualData.email,rechazado:serverTimestamp()})}
function obra(){if(!tienePermiso("obra"))return;const f=document.getElementById("obraForm"),l=document.getElementById("listaObra");if(!f)return;f.onsubmit=async e=>{e.preventDefault();await addDoc(collection(db,"obra"),{titulo:document.getElementById("obraTitulo").value.trim(),imagenUrl:document.getElementById("obraImagenUrl").value.trim(),descripcion:document.getElementById("obraDescripcion").value.trim(),creado:serverTimestamp()});f.reset()};onSnapshot(query(collection(db,"obra")),s=>{l.innerHTML="";s.forEach(d=>{const x=d.data();l.innerHTML+=`<div class="card"><h3>${x.titulo||"Obra"}</h3><p>${x.descripcion||""}</p></div>`})})}
function transparencia(){if(!tienePermiso("transparencia"))return;const f=document.getElementById("transparenciaForm"),l=document.getElementById("listaTransparenciaAdmin");if(!f)return;f.onsubmit=async e=>{e.preventDefault();await addDoc(collection(db,"transparencia"),{titulo:document.getElementById("transTitulo").value.trim(),monto:Number(document.getElementById("transMonto").value||0),url:document.getElementById("transUrl").value.trim(),descripcion:document.getElementById("transDescripcion").value.trim(),creado:serverTimestamp()});f.reset()};onSnapshot(query(collection(db,"transparencia")),s=>{l.innerHTML="";s.forEach(d=>{const x=d.data();l.innerHTML+=`<div class="card"><h3>${x.titulo||"Comprobante"}</h3><p>${x.descripcion||""}</p></div>`})})}
function usuarios(){if(!tienePermiso("usuarios"))return;const f=document.getElementById("usuarioForm"),l=document.getElementById("listaUsuarios");if(!f)return;f.onsubmit=async e=>{e.preventDefault();const email=document.getElementById("usuarioEmail").value.trim().toLowerCase();await setDoc(doc(db,"adminsByEmail",email),{nombre:document.getElementById("usuarioNombre").value.trim(),email,rol:"admin",activo:true,permisos:{institucional:document.getElementById("permInstitucional").checked,objetivos:document.getElementById("permObjetivos").checked,obra:document.getElementById("permObra").checked,transparencia:document.getElementById("permTransparencia").checked,usuarios:false},creado:serverTimestamp()});f.reset();alert("Administrador autorizado.")};onSnapshot(query(collection(db,"adminsByEmail")),s=>{l.innerHTML="";s.forEach(d=>{const x=d.data();l.innerHTML+=`<div class="admin-card"><h3>${x.nombre}</h3><p>${x.email}</p><p>${x.activo?"Activo":"Bloqueado"}</p></div>`})})}
